spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.83.128:5432/chinook-db
    username: sqluser
    password: D3v310p34202x-GD
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: never
server:
  port: 9090
#SWAGGER
springdoc:
  packages-to-scan: 'com.blumbit.web.api.store.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    com.blumbit.web.api.store: DEBUG
    org.hibernate: ERROR
  file:
    name: app-online-store.log


